# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              Amit Thakur 
tagline:            'This is a tagline'
description:        'Site description'
url:                 http://amitthakur.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Amit Thakur
  url:               http://amitthakur.org
  email:             hello@amitthakur.org

# Custom vars
version:             1.0.0
