# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:              Amit Thakur 
tagline:            'exploring ideas every single day'
description:        'Random musings on STEM (Science, Technology, Engineering, and Mathematics), art, and personal adventures'
url:                 http://amitthakur.org
baseurl:            ''
paginate:            5
plugins:               [jekyll-paginate]

# About/contact
author:
  name:              Amit Thakur
  url:               http://amitthakur.org
  email:             hello@amitthakur.org

# Custom vars
